# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Infiltrator's Hideout
subtitle: Offensive Security Blog
email:
description: >- # this means to ignore newlines until "baseurl:"
  Offensive Security Blog
twitter_username: username
github_username: username
minimal_mistakes_skin: dark
minimal_mistakes_skin2: default
words_per_minute: 150
search: true
search_provider: lunr
lunr:
  search_within_pages: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
algolia:
  powered_by: false



include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
url: "https://thr0cut.github.io"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-algolia

author:
  name   : "Thr0cut"
  avatar : "/docs/assets/images/bio-photo.jpg"
  bio    : "The unexpected guest"
  links:
    - label: "HackTheBox"
      icon: "fas fa-cube"
      url: "https://app.hackthebox.com/profile/1167918"
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discordapp.com/users/1169214046243917848"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
